### ISSUE TITLE
Add watermark feature, eg if someone uses a bytecode viewer they see the message, "Obfuscated by Bozar"

### ISSUE THREAD

**Issue by GreatZardasht** [vimasig/Bozar#1]
Title says all.

**Comment by vimasig** [comment]
There is already a watermark feature but not exactly what you said. When you open a class obfuscated with Bozar in notepad, you can see the watermark "Bozar".

Do you mean additional watermarks like:
- Dummy class named **"obfuscated with bozar"**.
- Renaming classes with the prefix **"bozar_"**.
- Inserting LDC, POP ( which is non-used string literals like **"obfuscated with bozar";** ) to the initializer of classes. (Modern decompilers ignore these things)
- Adding zip comment

or you didn't know that the watermark feature exists?

**Comment by GreatZardasht** [comment]
yes I meant LDC, POP
But the Zip comment and Dummy class sound like good features too

**Comment by vimasig** [comment]
We can't see these LDC POP things unless we use trash/outdated decompilers, so I'll not add it.
I'll add a watermark tab and configurable options to it. (Dummy class, zip comment, text inside class...)

👍👍

**Comment by GreatZardasht** [comment]
> We can't see these LDC POP things unless we use trash/outdated decompilers, so I'll not add it.
> I'll add a watermark tab and configurable options to it. (Dummy class, zip comment, text inside class...)
> 
> 👍👍

But wont the LDC, POP be seen by Bytecode viewers?

**Comment by vimasig** [comment]
We can do watermarks like dummy class which can be seen from everyone (both decompilers & bytecode viewers), I don't think we'll need to add a feature specifically for bytecode viewer.

**Comment by GreatZardasht** [comment]
> We can do watermarks like dummy class which can be seen from everyone (both decompilers & bytecode viewers), I don't think we'll need to add a feature specifically for bytecode viewer.

But the experienced people all use Bytecode viewers, it would be a cool feature as Bytecode viewers are still used, also when will the next release be out?

**Comment by vimasig** [comment]
Added & released.

**Comment by Comet6X** [comment]
@vimasig Do you know who this guy is lmao. He's tries to leaks minecraft clients and does this to public obfuscators so he knows what obfuscation they use.

**Comment by Napoleon-ZoomberParts** [comment]
> @vimasig Do you know who this guy is lmao. He's tries to leaks minecraft clients and does this to public obfuscators so he knows what obfuscation they use.

Omg someone is on to me 😳😳
