### ISSUE TITLE
Obfuscation problems

### ISSUE THREAD

**Issue by TheFirstPlaceCoder** [vimasig/Bozar#19]
![изображение](https://user-images.githubusercontent.com/110088936/197527499-b90cda0d-8f67-4b90-b68d-51b05d742ca9.png)

**Comment by vimasig** [comment]
Make sure you have write access to the path where you want to extract the output.
Also, it looks like [not appending the file name](https://stackoverflow.com/a/28673369) correctly causes that error too.
