### ISSUE TITLE
This is a rat lmfao

### ISSUE THREAD

**Issue by Andoo0** [vimasig/Bozar#21]
**Describe the bug**

**To Reproduce**
:) just stop being retarded and ratting a java obfuscator
**Expected behavior**
I havent expected a java obfuscator to be rat lol
**Screenshots**
<img width="359" alt="image" src="https://user-images.githubusercontent.com/101664057/210379221-15546302-114e-4654-a869-cc17d90d447a.png">
<img width="653" alt="image" src="https://user-images.githubusercontent.com/101664057/210379340-89b3325e-7719-43e3-b525-faa3ef3b6543.png">

**Bozar version**
1.4.0

**Additional context**
kids

**Comment by anjeshshrestha** [comment]
LAMOo, stop being retarded and remove your "GTA-5-Cheat.exe" and try the scan again 

https://www.virustotal.com/gui/file/d8385c91090ef9b4085e156e12008f9d140543ce4e4c65d6ddaffe9a5475034e

**Comment by vimasig** [comment]
I love you too
