### ISSUE TITLE
Constant obfuscation failing

### ISSUE THREAD

**Issue by KalioCraft** [vimasig/Bozar#4]
**Describe the bug**
When I try to obfuscate my project, everything looks fine in the decomplimiler, but I noticed that there are too few classes, and that showed. NoClassDefFoundError: It did not find the utils package. (No Renamer, No Shuffle)

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Bozar version**
v1.5

**Additional context**

**Comment by vimasig** [comment]
Do you get any errors in the console?
Which obfuscation option(s) is/are causing that issue?
Can you give me more information to reproduce that?

**Comment by KalioCraft** [comment]
Hey! Here are the Screenshots:
![Error](https://user-images.githubusercontent.com/71554802/120063190-457dc680-c066-11eb-9f98-7747c76dbcd8.PNG)
![Setting2](https://user-images.githubusercontent.com/71554802/120063192-46aef380-c066-11eb-9871-48debccceace.PNG)
![Setting1](https://user-images.githubusercontent.com/71554802/120063193-47e02080-c066-11eb-8720-a3521a61609b.PNG)

**Comment by vimasig** [comment]
It looks like Flow/Constant obfuscation (one of them or both) causing unprocessable frames.
But I need more information to find the cause.
I'll release an update that will produce detailed errors. Maybe we can get enough information from that.

**Comment by KalioCraft** [comment]
So, I've tested a bit here, and unfortunately I can't give you more information:
The class Obfuscation does not work at all: An exception comes: TypeNotPresentException: Type Cp not present in the class: Bozar.java (130) or Controller.java (120). The Flow Obfuscation works, but the Constant Obfuscation doesn't, I hope this helps you! LG

**Comment by vimasig** [comment]
Can you test v1.6? Hope we can get more detailed errors.

**Comment by KalioCraft** [comment]
The bug is still there: The console is spammed with "Cannot process class": 
![Unbenannt](https://user-images.githubusercontent.com/71554802/120481559-83edeb00-c3b0-11eb-90cb-952a1603671a.PNG)

**Comment by vimasig** [comment]
Can you run Bozar with this command line to print the output to a file and send me that?

Windows (using CMD):
```
Bozar.exe > output.txt 2>&1
```

Linux (using Terminal):
```
Bozar.run > output.txt 2>&1
```

Don't forget to navigate to the Bozar path using ```cd <bozar_path>``` command first

**Comment by vimasig** [comment]
Assuming you fixed the problem
