### ISSUE TITLE
Compile maven

### ISSUE THREAD

**Issue by Wiazz** [vimasig/Bozar#5]
**Describe the bug**
I get an error in maven

**To Reproduce**
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.666 s
[INFO] Finished at: 2021-07-01T05:37:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project Bozar: Fatal error compiling: invalid flag: --module-path -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Expected behavior**
to compile it for me

**Screenshots**
https://cdn.discordapp.com/attachments/657679887468855336/860016776536653844/unknown.png

**Bozar version**
1.6.0

**Additional context**
help me pls

**Comment by Wiazz** [comment]
PD: I use the version of maven:: Apache Maven 3.8.1

**Comment by vimasig** [comment]
Your maven JDK version is probably set to 8 (or even older?) while Bozar is using 16
Download JDK 16 and try [this fix](https://stackoverflow.com/a/46119209)

**Comment by Wiazz** [comment]
It already works correctly, thank you very much!
