### ISSUE TITLE
obfuscation failing 

### ISSUE THREAD

**Issue by sow-dev** [vimasig/Bozar#8]
**Describe the bug**
A clear and concise description of what the bug 

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Screenshots**

**Bozar version**
[e.g. 1.4.0]

**Additional context**
![image](https://user-images.githubusercontent.com/87903931/127653073-ef006822-ee3c-4c9a-aea6-b5722042ba7d.png)
[output.txt](https://github.com/vimasig/Bozar/files/6907527/output.txt)

**Comment by vimasig** [comment]
Error at photo and logs looks different.
Speaking for photo: It looks like you need to add library which contains javax.microedition.lcdui.Graphics class.
Speaking for logs: Looks like you are trying to obfuscate classes older than Java 7. I will not support you if your project is older than 1.7 but if you're trying to obfuscate a project which contains old libraries, try excluding them.

Let me know if you still get errors even if you tried these steps

**Comment by vimasig** [comment]
Closing, assuming it's fixed
